export const MY_SWITC_BOT_DEVICES = 'MY_SWITC_BOT_DEVICES';
export const MY_SWITC_BOT_TOKEN = 'MY_SWITC_BOT_TOKEN';

export const GET_DEVICES = 'GET_DEVICES';
export const DEVICE_POWER_ON = 'DEVICE_POWER_ON';
export const DEVICE_POWER_OFF = 'DEVICE_POWER_OFF';
